### ISSUE TITLE
What is "Slave Mode" and module doesn't show in COM port

### ISSUE THREAD

**Issue by sbarabe** [DFRobot/DFRobot_DF1201S#12]
Hi,

I've try to connect the module to my PC. When connected I can see the USB disk, but I cannot see it in COM port. So it's impossible to use the tool to configure the module with AT commands.

When I plug it, I can hear "Slave Mode", led is OFF.
If I push the button, I hear "Music" and blue led ON.

I've buy 3 modules, hope to find a way to configure them !

Thanks !

**Comment by qsjhyy** [comment]
![image](https://github.com/DFRobot/DFRobot_DF1201S/assets/78136558/ccafab4c-c7b3-461a-a33d-d1d888b50080)
usb can only store audio files, and AT commands need to be connected to uart.
![image](https://github.com/DFRobot/DFRobot_DF1201S/assets/78136558/2dd91fb2-eb1e-463f-974d-ec7a24c741f6)
If you want to connect to a pc, you should find a uart to USB auxiliary module.
More usage information can be found in this wiki: https://wiki.dfrobot.com/DFPlayer_PRO_SKU_DFR0768

**Comment by sbarabe** [comment]
Ok I understand, I need a converter USB-UART to give AT commands. Thank you !
