### ISSUE TITLE
resolution getCurTime() and getTotalTime()

### ISSUE THREAD

**Issue by tmjnijssen** [DFRobot/DFRobot_DF1201S#8]
The resolution of getCurTime() getTotalTime() appears to be just 8 bit, despite being presented as 16 bit. Eg, getTotalTime on a 10:44 long file returns 134. (10:44 = 644s , 644 % 255 = 134).

**Comment by tmjnijssen** [comment]
problem is the return type of `getINT()` being `uint8_t`

**Comment by tmjnijssen** [comment]
fixed by https://github.com/DFRobot/DFRobot_DF1201S/pull/9

**Comment by qsjhyy** [comment]
Thank you. You're right！
